---
language: python
branches:
  only:
    - master
# http://stackoverflow.com/questions/35625488/invalidrequirement-invalid-requirement-parse-error-error-after-updating-a-py
#TODO: this script could be pulled dynamically
install:
  - pip install -U pip
  - pip uninstall setuptools
  - pip install 'setuptools<20.2'
  - pip install -U pip setuptools
  - pip install -r requirements.txt
script:
  - python setup.py pkdeploy
