---
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - python setup.py tox
deploy:
  provider: pypi
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
  on:
    branch: ${PYPI_BRANCH}
  server: ${PYPI_SERVER}
  distributions: sdist
