---
language: python
branches:
  only:
    - master
#TODO: this script could be pulled dynamically
install:
  - pip install -U pip setuptools==32.1.3 tox
  - pip install -r requirements.txt
script:
  - python setup.py pkdeploy
